---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    name: kafka-1
    service: kafka
    broker_id: "1"
spec:
  # type: ClusterIP
  # clusterIP: 10.200.10.41
  ports:
    - name: broker
      port: 9092
  selector:
    name: kafka-1
    broker_id: "1"
