---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-1
  labels:
    name: kafka-1
    broker_id: "1"
spec:
  replicas: 1
  selector:
    name: kafka-1
    broker_id: "1"
  template:
    metadata:
      labels:
        name: kafka-1
        broker_id: "1"
        service: kafka
    spec:
      containers:
        - name: kafka
          image: quay.io/ukhomeofficedigital/kafka:v0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "1"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-1"
            - name: ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data
